package com.vehicleservices.spring.model;
// Generated Feb 17, 2019 1:56:18 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RefVehicleTypes generated by hbm2java
 */
@Entity
@Table(name="REF_VEHICLE_TYPES"
    ,schema="VEHICLE"
    ,catalog="VEHICLEDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="REF_VEHICLE_NO") 
)
public class RefVehicleTypes  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String vehicleTypeId;
     private int refVehicleNo;
     private String vehicleDesc;
     private Set<VehicleDetails> vehicleDetailses = new HashSet<VehicleDetails>(0);

    public RefVehicleTypes() {
    }

	
    public RefVehicleTypes(int refVehicleNo, String vehicleDesc) {
        this.refVehicleNo = refVehicleNo;
        this.vehicleDesc = vehicleDesc;
    }
    public RefVehicleTypes(int refVehicleNo, String vehicleDesc, Set<VehicleDetails> vehicleDetailses) {
       this.refVehicleNo = refVehicleNo;
       this.vehicleDesc = vehicleDesc;
       this.vehicleDetailses = vehicleDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="VEHICLE_TYPE_ID", unique=true, nullable=false, length=3)
    public String getVehicleTypeId() {
        return this.vehicleTypeId;
    }
    
    public void setVehicleTypeId(String vehicleTypeId) {
        this.vehicleTypeId = vehicleTypeId;
    }

    
    @Column(name="REF_VEHICLE_NO", unique=true, nullable=false)
    public int getRefVehicleNo() {
        return this.refVehicleNo;
    }
    
    public void setRefVehicleNo(int refVehicleNo) {
        this.refVehicleNo = refVehicleNo;
    }

    
    @Column(name="VEHICLE_DESC", nullable=false, length=45)
    public String getVehicleDesc() {
        return this.vehicleDesc;
    }
    
    public void setVehicleDesc(String vehicleDesc) {
        this.vehicleDesc = vehicleDesc;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="refVehicleTypes")
    public Set<VehicleDetails> getVehicleDetailses() {
        return this.vehicleDetailses;
    }
    
    public void setVehicleDetailses(Set<VehicleDetails> vehicleDetailses) {
        this.vehicleDetailses = vehicleDetailses;
    }




}


