package com.vehicleservices.spring.model;
// Generated Feb 17, 2019 1:56:18 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehicleDetails generated by hbm2java
 */
@Entity
@Table(name = "VEHICLE_DETAILS", schema = "VEHICLE", catalog = "VEHICLEDB")
public class VehicleDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer vehicleDetailsId;
	private RefVehicleTypes refVehicleTypes;
	private String vehicleName;
	private String make;
	private String model;
	private String modelYear;
	private Double price;
	private Date createdDate;
	private Date updatedDate;

	public VehicleDetails() {
	}

	public VehicleDetails(RefVehicleTypes refVehicleTypes, String vehicleName) {
		this.refVehicleTypes = refVehicleTypes;
		this.vehicleName = vehicleName;
	}

	public VehicleDetails(RefVehicleTypes refVehicleTypes, String vehicleName, String make, String model,
			String modelYear, Double price, Date createdDate, Date updatedDate) {
		this.refVehicleTypes = refVehicleTypes;
		this.vehicleName = vehicleName;
		this.make = make;
		this.model = model;
		this.modelYear = modelYear;
		this.price = price;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "VEHICLE_DETAILS_ID", unique = true, nullable = false)
	public Integer getVehicleDetailsId() {
		return this.vehicleDetailsId;
	}

	public void setVehicleDetailsId(Integer vehicleDetailsId) {
		this.vehicleDetailsId = vehicleDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEHICLE_TYPE_ID", nullable = false)
	public RefVehicleTypes getRefVehicleTypes() {
		return this.refVehicleTypes;
	}

	public void setRefVehicleTypes(RefVehicleTypes refVehicleTypes) {
		this.refVehicleTypes = refVehicleTypes;
	}

	@Column(name = "VEHICLE_NAME", nullable = false, length = 45)
	public String getVehicleName() {
		return this.vehicleName;
	}

	public void setVehicleName(String vehicleName) {
		this.vehicleName = vehicleName;
	}

	@Column(name = "MAKE", length = 45)
	public String getMake() {
		return this.make;
	}

	public void setMake(String make) {
		this.make = make;
	}

	@Column(name = "MODEL", length = 45)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "MODEL_YEAR", length = 4)
	public String getModelYear() {
		return this.modelYear;
	}

	public void setModelYear(String modelYear) {
		this.modelYear = modelYear;
	}

	@Column(name = "PRICE", precision = 17, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 26 , updatable=false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 26,insertable=false)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
